# Generated by Django 5.1.4 on 2025-01-11 07:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_groups_remove_user_groups_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="joinrequest",
            unique_together={("user", "group")},
        ),
    ]
