# Generated by Django 5.1.4 on 2025-01-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_joinrequest_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertasks",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
